version: '3.9'

services:
  dev-app:
    env_file: .env
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - dev-db
  dev-db:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - 5432:5432

